### ISSUE TITLE
Big map crashes

### ISSUE THREAD

**Issue by FabriceFABS** [mtroyka/SpringMapEdit#15]
When I want to make a new map and I take 30*40 size, it crashes.
I can however save it and still use menus, until I check [OK] on the following :
![crash](https://cloud.githubusercontent.com/assets/6024913/21092462/cdd95f2c-c04c-11e6-9524-a2dc12bae207.png)

I've set «maxmem=8192m» on startscript but this doesn't change...

**Comment by aeonios** [comment]
I tried making a giant map and the error was "out of memory". There's nothing I can do about that.
