### ISSUE TITLE
Choosing metal, type or vegetation breaks map rendering (map is fully black, nothing is rendered except the sun indicator)

### ISSUE THREAD

**Issue by gajop** [mtroyka/SpringMapEdit#18]

**Comment by gajop** [comment]
Correction, you can draw type stuff, but you have to guess where the map is

**Comment by aeonios** [comment]
View-> blend in texturemap

**Comment by aeonios** [comment]
although perhaps I should make that the default..

**Comment by gajop** [comment]
Definitely. Later you should probably make it draw something neutral (not the texture, e.g. just a grey background), so the terrain can be clearly seen
