### ISSUE TITLE
The Camera Sucks

### ISSUE THREAD

**Issue by aeonios** [mtroyka/SpringMapEdit#2]
SME has the most awful sadistic camera controls ever. There's no camera reset and it's also easy to get lost somewhere off in negative space, and thanks to the camera's lack of restrictions and horribly close near-plane clipping it can be impossible to find your way back to anywhere sensible. Even assuming that you don't get lost, just using it for basic map editing is an unholy pain in the ass, and the starting orientation is also horrible and difficult to relate to spring's default camera orientation.

Solution:
-Implement COFC-style controls for rotate and tilt and scroll-wheel zoom.
-(DONE) Fix the camera's default orientation to be congruent with spring.
-(DONE) Implement camera reset bound to tab.
-(DONE) Implement auto-setting for the camera far plane based on the map's dimensions, so that you never see far plane clipping.
-Implement camera position restrictions so that you can't wander too far off the map in any direction.

**Comment by Anarchid** [comment]
Yay blender camera!

**Comment by aeonios** [comment]
I'm going to call this fixed for now, via [this commit](https://github.com/mtroyka/SpringMapEdit/commit/cd74367297299e98f05c7f2a6afb5699033ed85c)

even though it's a fairly crude fix.
