### ISSUE TITLE
Single window interface

### ISSUE THREAD

**Issue by aeonios** [mtroyka/SpringMapEdit#5]
The current multi-window interface sucks. At the very least the main mode/brush window should be merged into the render window. Additionally the widgets in that window should no longer take keyboard input.

**Comment by FabriceFABS** [comment]
Is it regards the post I made on the forums ?

**Comment by aeonios** [comment]
Not really. I'm just jotting down whatever issues I can think of at the moment so I can remember what I need to do later. :P Using a single window interface is just common sense. XD

**Comment by FabriceFABS** [comment]
Alright ! :-)
